<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>CV TKI - {{ $tki->full_name }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 14px;
            color: #333;
            margin: 0;
            padding: 20px;
        }
        .header {
            text-align: center;
            border-bottom: 2px solid #2c3e50;
            padding-bottom: 10px;
            margin-bottom: 30px;
        }
        .header h1 {
            margin: 0;
            font-size: 24px;
            color: #2c3e50;
        }
        .header p {
            margin: 5px 0 0;
            font-size: 12px;
            color: #7f8c8d;
        }
        table {
            width: 100%;
            border-collapse: collapse;
        }
        td {
            padding: 12px;
            border-bottom: 1px solid #ecf0f1;
            vertical-align: top;
        }
        .label {
            width: 35%;
            font-weight: bold;
            color: #2c3e50;
            background-color: #f8f9fa;
        }
        .value {
            width: 65%;
            color: #34495e;
        }
        .section-title {
            margin-top: 30px;
            margin-bottom: 15px;
            font-size: 18px;
            color: #2980b9;
            border-bottom: 1px solid #2980b9;
            padding-bottom: 5px;
        }
    </style>
</head>
<body>

    <div class="header">
        <h1>BIODATA CALON PEKERJA MIGRAN INDONESIA</h1>
        <p>Generated by E-TKI System on {{ date('d M Y') }}</p>
    </div>

    <div class="section-title">Informasi Pribadi</div>
    <table>
        <tr>
            <td class="label">Nama Lengkap</td>
            <td class="value">{{ strtoupper($tki->full_name) }}</td>
        </tr>
        <tr>
            <td class="label">Nomor Paspor</td>
            <td class="value">{{ $tki->passport_number ?: '-' }}</td>
        </tr>
        <tr>
            <td class="label">Jenis Kelamin</td>
            <td class="value">{{ $tki->gender === 'L' ? 'Laki-laki' : 'Perempuan' }}</td>
        </tr>
        <tr>
            <td class="label">Tempat, Tanggal Lahir</td>
            <td class="value">
                {{ $tki->place_of_birth ?: '-' }}, 
                {{ $tki->date_of_birth ? \Carbon\Carbon::parse($tki->date_of_birth)->format('d F Y') : '-' }}
            </td>
        </tr>
        <tr>
            <td class="label">Status Pernikahan</td>
            <td class="value">{{ $tki->marital_status ?: '-' }}</td>
        </tr>
        <tr>
            <td class="label">Tinggi / Berat Badan</td>
            <td class="value">{{ $tki->height ?: '-' }} cm / {{ $tki->weight ?: '-' }} kg</td>
        </tr>
        <tr>
            <td class="label">Pendidikan Terakhir</td>
            <td class="value">{{ $tki->education ?: '-' }}</td>
        </tr>
        <tr>
            <td class="label">Alamat Lengkap</td>
            <td class="value">{{ $tki->address ?: '-' }}</td>
        </tr>
        <tr>
            <td class="label">Nama Ibu Kandung</td>
            <td class="value">{{ $tki->mother_name ?: '-' }}</td>
        </tr>
        <tr>
            <td class="label">Nama Pasangan</td>
            <td class="value">{{ $tki->spouse_name ?: '-' }}</td>
        </tr>
    </table>

    <div class="section-title">Informasi Penempatan</div>
    <table>
        <tr>
            <td class="label">Negara Tujuan</td>
            <td class="value">{{ $tki->destination_country ?: '-' }}</td>
        </tr>
        <tr>
            <td class="label">Pengalaman Kerja</td>
            <td class="value">{{ $tki->experience_type === 'EX' ? 'EX (Berpengalaman)' : 'NON (Belum Berpengalaman)' }}</td>
        </tr>
        <tr>
            <td class="label">Sponsor</td>
            <td class="value">{{ $tki->sponsor ? $tki->sponsor->name : '-' }}</td>
        </tr>
        <tr>
            <td class="label">Tanggal Pendaftaran</td>
            <td class="value">{{ $tki->registration_date ? \Carbon\Carbon::parse($tki->registration_date)->format('d F Y') : '-' }}</td>
        </tr>
        <tr>
            <td class="label">Status Verifikasi</td>
            <td class="value">{{ $tki->verification_status }}</td>
        </tr>
    </table>

</body>
</html>
